name: Test
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: ./test.sh
      - name: Print echo
        run: echo -e "test"